version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - elasticsearch
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=product_catalog
      - DB_USER=root
      - DB_PASS=password
      - ES_HOST=elasticsearch
      - ES_PORT=9200

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product_catalog
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./docker/mysql/init:/docker-entrypoint-initdb.d

  elasticsearch:
    image: elasticsearch:9.1.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data

  caddy:
    image: caddy:2.10-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./docker/certs:/data/caddy/certs
      - .:/var/www/html
    depends_on:
      - php
    restart: unless-stopped

volumes:
  mysql_data:
  es_data: